@startuml
title Ecosistema Musical Completo - Iteración Final

class Cantante {
                    }

class Disco {
}

class Cancion {
}

class Playlist {
}

class Instrumento {
}

class SelloDiscografico {
}

class Estudio {
}

Cantante -- Disco : Asociación
Disco *-- Cancion : Composición
Playlist o-- Cancion : Agregación
Cantante ..> Playlist : Uso
Cantante ..> Instrumento : Uso
SelloDiscografico o-- Disco : Agregación
Estudio ..> Cantante : Uso
Estudio ..> Instrumento : Uso

@enduml